ALTER TABLE users
  MODIFY COLUMN email VARCHAR(180) NULL;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS cpf VARCHAR(11) NULL AFTER whatsapp,
  ADD COLUMN IF NOT EXISTS crc_operator_area VARCHAR(80) NULL AFTER cpf;
