CREATE TABLE IF NOT EXISTS dental_card_leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data_indicacao DATE NULL,
  unidade VARCHAR(180) NOT NULL,
  nome_lead VARCHAR(180) NOT NULL,
  telefone VARCHAR(40) NOT NULL,
  ficha VARCHAR(80) NULL,
  nome_indicador VARCHAR(180) NULL,
  tipo_indicador VARCHAR(80) NULL,
  dentista_responsavel VARCHAR(180) NULL,
  origem VARCHAR(120) NULL,
  responsavel VARCHAR(180) NULL,
  responsavel_user_id INT NULL,
  status VARCHAR(80) NOT NULL DEFAULT 'Novo Lead',
  status_contato VARCHAR(80) NULL,
  canal_contato VARCHAR(80) NULL,
  quantidade_tentativas INT NOT NULL DEFAULT 0,
  data_primeiro_contato DATETIME NULL,
  data_ultima_tentativa DATETIME NULL,
  data_proxima_tentativa DATETIME NULL,
  agendado TINYINT(1) NOT NULL DEFAULT 0,
  agendado_por VARCHAR(80) NULL,
  data_agendamento DATE NULL,
  hora_agendamento TIME NULL,
  ecuro_lancado TINYINT(1) NOT NULL DEFAULT 0,
  endereco_enviado TINYINT(1) NOT NULL DEFAULT 0,
  confirmacao_enviada TINYINT(1) NOT NULL DEFAULT 0,
  confirmou_presenca VARCHAR(40) NULL,
  compareceu TINYINT(1) NOT NULL DEFAULT 0,
  motivo_falta VARCHAR(500) NULL,
  tentativa_recuperacao TINYINT(1) NOT NULL DEFAULT 0,
  data_reagendamento DATE NULL,
  pagou VARCHAR(40) NOT NULL DEFAULT 'pendente',
  valor_pago DECIMAL(14,2) NOT NULL DEFAULT 0,
  forma_pagamento VARCHAR(80) NULL,
  receita DECIMAL(14,2) NOT NULL DEFAULT 0,
  pesquisa_satisfacao_enviada TINYINT(1) NOT NULL DEFAULT 0,
  nova_indicacao_solicitada TINYINT(1) NOT NULL DEFAULT 0,
  nova_indicacao_recebida TINYINT(1) NOT NULL DEFAULT 0,
  observacoes TEXT NULL,
  sla_status VARCHAR(40) NOT NULL DEFAULT 'ok',
  dias_sem_contato INT NOT NULL DEFAULT 0,
  encerrado_em DATETIME NULL,
  encerrado_por VARCHAR(180) NULL,
  motivo_encerramento VARCHAR(500) NULL,
  created_by VARCHAR(180) NULL,
  updated_by VARCHAR(180) NULL,
  deleted_at TIMESTAMP NULL,
  deleted_by VARCHAR(180) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_dental_card_data (data_indicacao),
  INDEX idx_dental_card_unidade (unidade),
  INDEX idx_dental_card_status (status),
  INDEX idx_dental_card_telefone (telefone),
  INDEX idx_dental_card_proxima (data_proxima_tentativa)
);

CREATE TABLE IF NOT EXISTS dental_card_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  responsavel VARCHAR(180) NULL,
  responsavel_user_id INT NULL,
  tipo_contato VARCHAR(80) NULL,
  canal VARCHAR(80) NULL,
  resultado VARCHAR(120) NULL,
  observacao TEXT NULL,
  proxima_acao VARCHAR(180) NULL,
  data_proxima_acao DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_dental_attempt_lead (lead_id),
  CONSTRAINT fk_dental_attempt_lead FOREIGN KEY (lead_id) REFERENCES dental_card_leads(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dental_card_message_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(160) NOT NULL,
  tipo VARCHAR(80) NOT NULL,
  mensagem TEXT NOT NULL,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  created_by VARCHAR(180) NULL,
  updated_by VARCHAR(180) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_dental_card_template_tipo (tipo)
);

CREATE TABLE IF NOT EXISTS dental_card_audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NULL,
  user_id INT NULL,
  user_name VARCHAR(180) NULL,
  user_role VARCHAR(80) NULL,
  action VARCHAR(120) NOT NULL,
  ip VARCHAR(80) NULL,
  details LONGTEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_dental_audit_lead (lead_id),
  INDEX idx_dental_audit_action (action)
);
