CREATE TABLE IF NOT EXISTS ecuro_robot_jobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  job_type VARCHAR(80) NOT NULL,
  clinic_id INT NULL,
  clinic_name VARCHAR(180) NULL,
  appointment_date DATE NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  total_checked INT NOT NULL DEFAULT 0,
  total_completed INT NOT NULL DEFAULT 0,
  total_failed INT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  artifacts_json LONGTEXT NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_by VARCHAR(180) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ecuro_robot_jobs_status (status, created_at),
  INDEX idx_ecuro_robot_jobs_clinic (clinic_id, appointment_date)
);

CREATE TABLE IF NOT EXISTS ecuro_patient_completion_status (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  job_id BIGINT NOT NULL,
  clinic_id INT NULL,
  clinic_name VARCHAR(180) NULL,
  patient_name VARCHAR(180) NULL,
  patient_phone VARCHAR(40) NULL,
  appointment_date DATE NULL,
  appointment_time VARCHAR(20) NULL,
  external_patient_id VARCHAR(120) NULL,
  external_status VARCHAR(120) NULL,
  completion_status VARCHAR(40) NOT NULL DEFAULT 'not_found',
  matched_by VARCHAR(40) NULL,
  confidence_score DECIMAL(5,2) NULL,
  agenda_item_id INT NULL,
  raw_payload_json LONGTEXT NULL,
  checked_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ecuro_completion_job (job_id),
  INDEX idx_ecuro_completion_status (completion_status, clinic_id),
  INDEX idx_ecuro_completion_lookup (clinic_id, appointment_date, patient_name)
);

CREATE TABLE IF NOT EXISTS nps_invites (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(160) NOT NULL,
  clinic_id INT NULL,
  clinic_name VARCHAR(180) NULL,
  patient_name VARCHAR(180) NULL,
  patient_phone VARCHAR(40) NULL,
  appointment_id INT NULL,
  ecuro_completion_id BIGINT NULL,
  source VARCHAR(80) NOT NULL DEFAULT 'ecuro_robot',
  session_id VARCHAR(120) NOT NULL DEFAULT 'nps',
  status VARCHAR(40) NOT NULL DEFAULT 'pending',
  public_url TEXT NULL,
  provider_message_id VARCHAR(180) NULL,
  idempotency_key VARCHAR(180) NOT NULL,
  error_message TEXT NULL,
  attempts INT NOT NULL DEFAULT 0,
  last_attempt_at DATETIME NULL,
  next_attempt_at DATETIME NULL,
  sent_at DATETIME NULL,
  responded_at DATETIME NULL,
  created_by VARCHAR(180) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_nps_invites_token (token),
  UNIQUE KEY uniq_nps_invites_idempotency (idempotency_key),
  INDEX idx_nps_invites_status (status, session_id, next_attempt_at),
  INDEX idx_nps_invites_phone_day (patient_phone, created_at),
  INDEX idx_nps_invites_completion (ecuro_completion_id)
);
